name: Build, Analyze and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Build Docker Image (Installe les dépendances via le Dockerfile)
      - name: Build Docker Image
        run: |
          # Assurez-vous d'utiliser le bon contexte de répertoire pour le build
          docker buildx create --use   # Créer et utiliser un builder pour buildx
          docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest . --push  # Construire et pousser l'image directement
          docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }} . --push  # Utilisation de GitHub SHA pour taguer

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker Image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}
