name: Build, Analyze and Push Docker Image

on:
  push:
    branches:
      - main  # S'exécute lors d'un push sur la branche 'main'
  pull_request:
    branches:
      - main  # S'exécute lors d'un pull request vers la branche 'main'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour les actions

    steps:
      # Etape 1: Checkout le code depuis le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Etape 2: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Spécifie la version de Node.js

      # Etape 3: Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Etape 4: Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}

      # Etape 5: Connexion à DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Etape 6: Pousser l'image Docker vers DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}
