name: Build, Analyze and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (optional if not needed for other steps)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          # Create and use a builder instance for buildx
          docker buildx create --use

          # Build and push the latest version of the image
          docker buildx build \
            -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest \
            --push .

          # Build and push the image with a specific GitHub SHA tag
          docker buildx build \
            -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:d1e7171b76111685b64ed1058b2b80f1d35dc91e \
            --push .